<Project Sdk="Dalamud.NET.Sdk/15.0.0">
	<PropertyGroup>
		<Authors>Chirp</Authors>
		<Version>0.2.7</Version>
		<Platforms>x64</Platforms>
		<TargetFramework>net10.0-windows</TargetFramework>
	</PropertyGroup>

	<PropertyGroup Condition="Exists('$(DALAMUD_HOME)') OR '$(OS)' != 'Windows_NT' OR '$(CI)' == 'true'">
		<DalamudLibPath>$(DALAMUD_HOME)/</DalamudLibPath>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\GLib\GLib\GLib.csproj" />
	</ItemGroup>
</Project>